package(default_visibility = ["//visibility:public"])

filegroup(
    name = "package-srcs",
    srcs = glob(["**"]) + [
        "//tools/build_defs/d:srcs",
        "//tools/build_defs/docker:srcs",
        "//tools/build_defs/jsonnet:srcs",
        "//tools/build_defs/pkg:srcs",
        "//tools/build_defs/sass:srcs",
        "//tools/build_rules/appengine:srcs",
        "//tools/build_rules/closure:srcs",
        "//tools/build_rules/go:srcs",
        "//tools/build_rules/rust:srcs",
    ],
)

filegroup(
    name = "embedded_tools_srcs",
    srcs = glob(["**"]) + [
        "//tools/build_defs/d:srcs",
        "//tools/build_defs/docker:srcs",
        "//tools/build_defs/jsonnet:srcs",
        "//tools/build_rules/appengine:srcs",
        "//tools/build_rules/closure:srcs",
        "//tools/build_rules/rust:srcs",
    ],
)
